image: "python:3.10"

before_script:
  - pip install -r requirements.txt

stages:
  - Static Analysis
  - Test
  - Deploy

pylint:
  stage: Static Analysis
  only:
  - dev
  - main
  script:
    - pylint -d C0301 src/*.py

pytest:
  stage: Test
  only:
  - dev
  - main
  script:
    - pytest test/ -v

Deploy:
  stage: Deploy
  only:
  - main
  script:
  - cd src/
  - pyinstaller -F main.py
  artifacts:
    paths:
      - src/dist/*.exe